import { Document } from "@shared/schema";
import PDFDocument from "pdfkit";
import { Document as DocxDocument, Packer, Paragraph, TextRun, HeadingLevel } from "docx";

export class DocumentGenerator {
  async generateDocument(document: Document, format: 'pdf' | 'docx'): Promise<Buffer> {
    if (format === 'pdf') {
      return this.generatePDF(document);
    } else {
      return this.generateDOCX(document);
    }
  }

  private async generatePDF(document: Document): Promise<Buffer> {
    return new Promise((resolve, reject) => {
      try {
        const doc = new PDFDocument({ margin: 50 });
        const chunks: Buffer[] = [];

        doc.on('data', (chunk: any) => chunks.push(chunk));
        doc.on('end', () => resolve(Buffer.concat(chunks)));
        doc.on('error', reject);

        const data = document.extractedData as any;

        // Company Header
        doc.fontSize(20).fillColor('#3B82F6').text('Apex Chemicals Corp.', 50, 50);
        doc.fontSize(12).fillColor('#6B7280').text('Advanced Chemical Solutions', 50, 75);
        
        // Document Info
        doc.fontSize(10).fillColor('#6B7280');
        doc.text(`Generated: ${new Date().toLocaleDateString()}`, 400, 50);
        doc.text(`Doc ID: AC-${data?.document?.id || 'Unknown'}`, 400, 65);

        let yPosition = 120;

        // Product Identification
        doc.fontSize(14).fillColor('#1E40AF').text('PRODUCT IDENTIFICATION', 50, yPosition);
        yPosition += 25;
        
        doc.fontSize(10).fillColor('#000000');
        doc.text(`Product Name: ${data?.product?.name || 'Unknown'}`, 50, yPosition);
        doc.text(`CAS Number: ${data?.product?.casNumber || 'Unknown'}`, 300, yPosition);
        yPosition += 15;
        doc.text(`Formula: ${data?.product?.formula || 'Unknown'}`, 50, yPosition);
        doc.text(`Grade: ${data?.product?.grade || 'Unknown'}`, 300, yPosition);
        yPosition += 30;

        // Supplier Information
        doc.fontSize(14).fillColor('#1E40AF').text('SUPPLIER INFORMATION', 50, yPosition);
        yPosition += 25;
        
        doc.fontSize(10).fillColor('#000000');
        doc.text(`Company: ${data?.supplier?.name || 'Unknown'}`, 50, yPosition);
        yPosition += 15;
        doc.text(`Address: ${data?.supplier?.address || 'Unknown'}`, 50, yPosition);
        yPosition += 15;
        doc.text(`Phone: ${data?.supplier?.phone || 'Unknown'}`, 50, yPosition);
        doc.text(`Emergency: ${data?.supplier?.emergency || 'Unknown'}`, 300, yPosition);
        yPosition += 30;

        // Hazard Information
        doc.fontSize(14).fillColor('#DC2626').text('HAZARD IDENTIFICATION', 50, yPosition);
        yPosition += 25;
        
        if (data?.hazards && data.hazards.length > 0) {
          data.hazards.forEach((hazard: any) => {
            doc.fontSize(10).fillColor('#000000');
            doc.text(`• ${hazard.category} - ${hazard.signal}`, 50, yPosition);
            yPosition += 15;
          });
        } else {
          doc.fontSize(10).fillColor('#6B7280').text('No hazard information available', 50, yPosition);
        }

        // Footer
        yPosition = doc.page.height - 100;
        doc.fontSize(8).fillColor('#6B7280');
        doc.text('This document was generated by Apex Chemicals Corp. automated processing system.', 50, yPosition, { align: 'center' });
        doc.text('For questions or concerns, contact our technical support team.', 50, yPosition + 15, { align: 'center' });

        doc.end();
      } catch (error) {
        reject(error);
      }
    });
  }

  private async generateDOCX(document: Document): Promise<Buffer> {
    const data = document.extractedData as any;

    const doc = new DocxDocument({
      sections: [{
        properties: {},
        children: [
          // Company Header
          new Paragraph({
            children: [
              new TextRun({
                text: "Apex Chemicals Corp.",
                bold: true,
                size: 32,
                color: "3B82F6"
              })
            ]
          }),
          new Paragraph({
            children: [
              new TextRun({
                text: "Advanced Chemical Solutions",
                size: 20,
                color: "6B7280"
              })
            ]
          }),
          new Paragraph({ text: "" }), // Empty line

          // Product Identification
          new Paragraph({
            children: [
              new TextRun({
                text: "PRODUCT IDENTIFICATION",
                bold: true,
                size: 24,
                color: "1E40AF"
              })
            ],
            heading: HeadingLevel.HEADING_2
          }),
          new Paragraph({
            children: [
              new TextRun({ text: "Product Name: ", bold: true }),
              new TextRun({ text: data?.product?.name || "Unknown" })
            ]
          }),
          new Paragraph({
            children: [
              new TextRun({ text: "CAS Number: ", bold: true }),
              new TextRun({ text: data?.product?.casNumber || "Unknown" })
            ]
          }),
          new Paragraph({
            children: [
              new TextRun({ text: "Formula: ", bold: true }),
              new TextRun({ text: data?.product?.formula || "Unknown" })
            ]
          }),
          new Paragraph({
            children: [
              new TextRun({ text: "Grade: ", bold: true }),
              new TextRun({ text: data?.product?.grade || "Unknown" })
            ]
          }),
          new Paragraph({ text: "" }), // Empty line

          // Supplier Information
          new Paragraph({
            children: [
              new TextRun({
                text: "SUPPLIER INFORMATION",
                bold: true,
                size: 24,
                color: "1E40AF"
              })
            ],
            heading: HeadingLevel.HEADING_2
          }),
          new Paragraph({
            children: [
              new TextRun({ text: "Company: ", bold: true }),
              new TextRun({ text: data?.supplier?.name || "Unknown" })
            ]
          }),
          new Paragraph({
            children: [
              new TextRun({ text: "Address: ", bold: true }),
              new TextRun({ text: data?.supplier?.address || "Unknown" })
            ]
          }),
          new Paragraph({
            children: [
              new TextRun({ text: "Phone: ", bold: true }),
              new TextRun({ text: data?.supplier?.phone || "Unknown" })
            ]
          }),
          new Paragraph({
            children: [
              new TextRun({ text: "Emergency: ", bold: true }),
              new TextRun({ text: data?.supplier?.emergency || "Unknown" })
            ]
          }),
          new Paragraph({ text: "" }), // Empty line

          // Hazard Information
          new Paragraph({
            children: [
              new TextRun({
                text: "HAZARD IDENTIFICATION",
                bold: true,
                size: 24,
                color: "DC2626"
              })
            ],
            heading: HeadingLevel.HEADING_2
          }),
          ...(data?.hazards && data.hazards.length > 0 ? 
            data.hazards.map((hazard: any) => 
              new Paragraph({
                children: [
                  new TextRun({ text: `• ${hazard.category} - ${hazard.signal}` })
                ]
              })
            ) : 
            [new Paragraph({
              children: [
                new TextRun({ 
                  text: "No hazard information available",
                  color: "6B7280"
                })
              ]
            })]
          ),
          new Paragraph({ text: "" }), // Empty line

          // Footer
          new Paragraph({
            children: [
              new TextRun({
                text: "This document was generated by Apex Chemicals Corp. automated processing system.",
                size: 16,
                color: "6B7280"
              })
            ]
          }),
          new Paragraph({
            children: [
              new TextRun({
                text: "For questions or concerns, contact our technical support team.",
                size: 16,
                color: "6B7280"
              })
            ]
          })
        ]
      }]
    });

    return await Packer.toBuffer(doc);
  }
}
